### ISSUE TITLE
ValidationError from generate_statistics_from_tfrecord pipeline

### ISSUE THREAD

**Issue by jagthebeetle** [tensorflow/data-validation#105]
We are running a `generate_statistics_from_tfrecord` pipeline that fails when run on Dataflow with a `ValidationError`

Pipeline code:
```
PROJECT = 'project'
JOB_NAME = 'job'
REGION = 'region'
N_WORKERS = None
GCS_TMP_LOCATION = 'gs://path/to/tmp'
GCS_DATA_LOCATION_BLOB = 'gs://path/to/*.tfrecord.gz'
# GCS_STATS_OUTPUT_PATH is the file path to which to output the data statistics
# result.
GCS_STATS_OUTPUT_PATH = 'gs://path/to/output'

# Create and set your PipelineOptions.
options = PipelineOptions()

pipeline_options_kwargs = {
  'runner': 'DataflowRunner',
  'project': PROJECT,
  'job_name': JOB_NAME,
  'region': REGION,
  'temp_location': GCS_TMP_LOCATION,
  'network': 'vpc',
  'subnetwork': 'https://www.googleapis.com/compute/v1/path/to/subnet',
  'use_public_ips': False,
  'save_main_session': True,
  'experiments': ['shuffle_mode=service'],
  'service_account_email': 'serviceaccount@project.iam.gserviceaccount.com',
  'autoscaling_algorithm': 'NONE' if N_WORKERS is not None else None,
  'num_workers': N_WORKERS,
  'setup_file': './dataflow_dependencies/setup.py'
}
pipeline_options = PipelineOptions(flags=[], **pipeline_options_kwargs)

stats = tfdv.generate_statistics_from_tfrecord(
  GCS_DATA_LOCATION_BLOB,
  output_path=GCS_STATS_OUTPUT_PATH,
  pipeline_options=pipeline_options
)
```

Error:
```
Progress reporting thread got error: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/batchworker.py", line 234, in progress_reporting_thread
    state_sampler_info=state_sampler_info)
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/batchworker.py", line 341, in report_status
    work_executor=self._work_executor)
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/workerapiclient.py", line 420, in report_status
    work_item_status)
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/workerapiclient.py", line 323, in _append_all_user_metric_updates
    metric_kind=dataflow.CounterMetadata.KindValueValuesEnum.SUM)
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/workerapiclient.py", line 243, in _update_metrics
    status_object, metric_name, metric_kind, value=update, setter=setter)
  File "/usr/local/lib/python3.5/site-packages/dataflow_worker/workerapiclient.py", line 143, in append_counter_update
    setter(value, metric_update)
  File "/usr/local/lib/python3.5/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 853, in translate_value
    metric_update_proto.integer = to_split_int(value)
  File "/usr/local/lib/python3.5/site-packages/apache_beam/runners/dataflow/internal/apiclient.py", line 827, in to_split_int
    res.lowBits = n & 0xffffffff
  File "/usr/local/lib/python3.5/site-packages/apitools/base/protorpclite/messages.py", line 973, in __setattr__
    object.__setattr__(self, name, value)
  File "/usr/local/lib/python3.5/site-packages/apitools/base/protorpclite/messages.py", line 1293, in __set__
    value = self.validate(value)
  File "/usr/local/lib/python3.5/site-packages/apitools/base/protorpclite/messages.py", line 1400, in validate
    return self.__validate(value, self.validate_element)
  File "/usr/local/lib/python3.5/site-packages/apitools/base/protorpclite/messages.py", line 1358, in __validate
    return validate_element(value)
  File "/usr/local/lib/python3.5/site-packages/apitools/base/protorpclite/messages.py", line 1340, in validate_element
    (self.type, name, value, type(value)))
apitools.base.protorpclite.messages.ValidationError: Expected type (<class 'int'>,) for field lowBits, found 1 (type <class 'numpy.int64'>)
```

Based on method names in the traceback, it seems like TFDV might be setting beam.metrics that take on `numpy.int64` values, which Dataflow then does not like.

Looking through the code, I see two main sites where beam.metrics are used, though there may be more:
https://github.com/tensorflow/data-validation/blob/40b29a57afbf90d5a9fb2f6f1cd1972f216b5f97/tensorflow_data_validation/statistics/generators/basic_stats_generator.py#L655
https://github.com/tensorflow/data-validation/blob/425beeab53fb6f615bb7387408bd208532c7fe01/tensorflow_data_validation/statistics/stats_impl.py#L570

Note that we have frozen and staged our dependencies onto Dataflow (no online installation), but this error is not immediately suggestive of a stale dependency or conflict.
We are using `Apache Beam Python 3.5 SDK 2.14.0`.

**Comment by jagthebeetle** [comment]
Ah, it's probable we were using a version of tfdv prior to the one containing a cast to int in one of the metric-setting routines; using the most recent version fixes this.

https://github.com/tensorflow/data-validation/commit/b6329ba5c7696908326362feb94f9e1c68bd62ff#diff-bdb28b552d5b42a52c5f6c30ce56677c
