### ISSUE TITLE
Why tensorflow_data_validation seems like it is not working?

### ISSUE THREAD

**Issue by mail2chromium** [tensorflow/data-validation#121]
I am trying to use the *Tensorflow_data_validation* module for exploring and validating some machine learning data. But It seems like the `tensorflow_data_validation` module is no more working. I have tried using:

```
import tensorflow_data_validation as tfdv

# train_stats = tfdv.generate_statistics_from_tfrecord(data_location='googleplaystore.csv')
# train_stats_for_csv = tfdv.generate_statistics_from_csv(data_location='googleplaystore.csv')
train_stats_for_datFrame = tfdv.generate_statistics_from_dataframe(data_location='googleplaystore.csv')
```

Every time, it is throwing these following errors:

- AttributeError: module 'tensorflow_data_validation' has no attribute 'generate_statistics_from_tfrecord'

- AttributeError: module 'tensorflow_data_validation' has no attribute 'generate_statistics_from_csv'

- AttributeError: module 'tensorflow_data_validation' has no attribute 'generate_statistics_from_dataframe'

------

**Addition Information:**

- OS: Microsoft Windows 10-Pro
- Python: 3.8.0
- tensorflow-data-validation == 0.21.5
- tensorflow-transform-0.3.1

-----

**Error Logs:**

```
C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\python.exe F:/PythonCodeBase/Stack-Overflow-Part-2/Tensorflow/test.py
2020-04-14 00:27:45.246218: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "F:/PythonCodeBase/Stack-Overflow-Part-2/Tensorflow/test.py", line 2, in <module>
    import tensorflow_data_validation as tfdv
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\tensorflow_data_validation\__init__.py", line 24, in <module>
    from tensorflow_data_validation.api.stats_api import GenerateStatistics
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\tensorflow_data_validation\api\stats_api.py", line 48, in <module>
    import apache_beam as beam
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\apache_beam\__init__.py", line 97, in <module>
    from apache_beam import coders
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\apache_beam\coders\__init__.py", line 19, in <module>
    from apache_beam.coders.coders import *
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\apache_beam\coders\coders.py", line 43, in <module>
    from future.moves import pickle
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\future\moves\__init__.py", line 8, in <module>
    import_top_level_modules()
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\future\standard_library\__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "C:\ProgramData\Anaconda3\envs\Stack-Over-Flow\lib\site-packages\future\standard_library\__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "F:\PythonCodeBase\Stack-Overflow-Part-2\Tensorflow\test.py", line 9, in <module>
    train_stats_for_datFrame = tfdv.generate_statistics_from_dataframe(data_location='googleplaystore.csv')
AttributeError: module 'tensorflow_data_validation' has no attribute 'generate_statistics_from_dataframe'

Process finished with exit code 1

```
Can anyone please help me?

**Comment by mh2t** [comment]
```
pip install fairness-indicators \
  "absl-py" \
  "pyarrow" \
  "apache-beam" \
  "avro-python3"

%tensorflow_version 2.x
import os
import tempfile
import apache_beam as beam
import numpy as np
import pandas as pd
from datetime import datetime

import tensorflow_hub as hub
import tensorflow as tf
import tensorflow_model_analysis as tfma
import tensorflow_data_validation as tfdv
from tensorflow_model_analysis.addons.fairness.post_export_metrics import fairness_indicators
from tensorflow_model_analysis.addons.fairness.view import widget_view
from fairness_indicators.examples import util

from witwidget.notebook.visualization import WitConfigBuilder
from witwidget.notebook.visualization import WitWidget

stats = tfdv.generate_statistics_from_tfrecord(data_location=myTFRecord)
tfdv.visualize_statistics(stats)
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/apache_beam/runners/worker/sdk_worker.py in get(self, instruction_id, bundle_descriptor_id)
    311       # pop() is threadsafe
--> 312       processor = self.cached_bundle_processors[bundle_descriptor_id].pop()
    313     except IndexError:

IndexError: pop from empty list

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
33 frames
AttributeError: module 'tfx_bsl.coders.example_coder' has no attribute 'ExamplesToRecordBatchDecoder'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_data_validation/utils/batch_util.py in setup(self)
     98 
     99   def setup(self):
--> 100     self._decoder = example_coder.ExamplesToRecordBatchDecoder()
    101 
    102   def process(self, batch: List[bytes]) -> Iterable[pa.RecordBatch]:

AttributeError: module 'tfx_bsl.coders.example_coder' has no attribute 'ExamplesToRecordBatchDecoder' [while running 'DecodeData/BatchSerializedExamplesToArrowRecordBatches/BatchDecodeExamples']
```

Can anyone help me on this error? I'm using Colab.

**Comment by arghyaganguly** [comment]
Error is not reproducible in latest tfdv==0.28.0.Tested in ubuntu 18.04.Closing this.
Please feel free to reopen if required.
