### ISSUE TITLE
generate_statistics_from_tfrecord doesn't work on large-scale data with Direct Runner(beam) because of grpc timeout

### ISSUE THREAD

**Issue by xjj59307** [tensorflow/data-validation#133]
I'm struggling with running tfdv.generate_statistics_from_tfrecord against a large-scale dataset which is over 400GB.
Since I succeeded in processing a relatively small dataset of 100GB, I don't think it's an issue related to the dataset.

```
tfdv.generate_statistics_from_tfrecord(
    data_location="./tfrecord/part-*",
    pipeline_options=PipelineOptions(['--direct_num_workers', '0', '--direct_running_mode', 'multi_processing'])
)
```

It always ends with the following errors. The process doesn't exit though.

```
E0804 17:49:07.419950276   44806 chttp2_transport.cc:2881]   ipv6:[::1]:40823: Keepalive watchdog fired. Closing transport.
2020-08-04 17:49:07  local_job_service.py : INFO  Worker: severity: ERROR timestamp {   seconds: 1596563347   nanos: 420487403 } message: "Python sdk harness failed: \nTraceback (most recent call last):\n  File \"/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker_main.py\", line 158, in main\n    sdk_pipeline_options.view_as(ProfilingOptions))).run()\n  File \"/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py\", line 213, in run\n    for work_request in self._control_stub.Control(get_responses()):\n  File \"/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py\", line 416, in __next__\n    return self._next()\n  File \"/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py\", line 706, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"keepalive watchdog timeout\"\n\tdebug_error_string = \"{\"created\":\"@1596563347.420024732\",\"description\":\"Error received from peer ipv6:[::1]:40823\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1055,\"grpc_message\":\"keepalive watchdog timeout\",\"grpc_status\":14}\"\n>" trace: "Traceback (most recent call last):\n  File \"/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker_main.py\", line 158, in main\n    sdk_pipeline_options.view_as(ProfilingOptions))).run()\n  File \"/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py\", line 213, in run\n    for work_request in self._control_stub.Control(get_responses()):\n  File \"/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py\", line 416, in __next__\n    return self._next()\n  File \"/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py\", line 706, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"keepalive watchdog timeout\"\n\tdebug_error_string = \"{\"created\":\"@1596563347.420024732\",\"description\":\"Error received from peer ipv6:[::1]:40823\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1055,\"grpc_message\":\"keepalive watchdog timeout\",\"grpc_status\":14}\"\n>\n" log_location: "/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker_main.py:161" thread: "MainThread"
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globalse
  File "/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker_main.py", line 248, in <module>
    main(sys.argv)
  File "/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker_main.py", line 158, in main
    sdk_pipeline_options.view_as(ProfilingOptions))).run()
  File "/home/ec2-user/lib64/python3.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 213, in run
    for work_request in self._control_stub.Control(get_responses()):
  File "/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/home/ec2-user/lib64/python3.7/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "keepalive watchdog timeout"
        debug_error_string = "{"created":"@1596563347.420024732","description":"Error received from peer ipv6:[::1]:40823","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
```

The process was getting stuck forever. From top command, I can see no worker process is running. And from pystack, it seems that the application process is timing out on all workers.

```
  File "/usr/lib64/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/lib64/python3.7/site-packages/grpc/_server.py", line 871, in _serve
    event = state.completion_queue.poll(timeout)
```

**Comment by caveness** [comment]
Hi -- I expect this is an issue with DirectRunner being able to handle such a large dataset. DirectRunner is designed to debug/validate pipelines using smaller datasets, but doesn't focus on efficient pipeline execution. See https://beam.apache.org/documentation/runners/direct/.

As you move to running TFDV on larger datasets, can you try using a using a distributed environment (e.g., Dataflow)? See https://www.tensorflow.org/tfx/data_validation/get_started#running_on_google_cloud.

**Comment by xjj59307** [comment]
@caveness Hi, thank you for the reply :)
I think Direct Runner has its merits, it's running pretty fast on over 100GB data and easy to use.
Here it doesn't seem to be a real issue but needs some tuning on parameters, probably setting a larger grpc timeout? I couldn't figure out how to make it though.

Using gcp service like Dataflow is a little difficult for me :(
Is tfdv tested against other runners like spark runner?

**Comment by caveness** [comment]
Hi -- Unfortunately, I don't have suggestions for how to get this to work with DirectRunner, as I believe it has to do with the runner's ability to process the data at issue as opposed to TFDV-specific considerations. You might try posting this question to Beam, as they may be able to provide more advice about how to handle this.

Although TFDV isn't tested against individual runners such as Spark runner, there shouldn't be any TFDV-specific limitations on running on Beam-supported runners.

**Comment by xjj59307** [comment]
@caveness Thank you very much for your kind reply. Let me close the issue then.

**Comment by zippeurfou** [comment]
@xjj59307 I am circling back to you on this. Did you ever find a solution that works for you?
