### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [tensorflow/data-validation#141]
**Summary**
Installing tensorflow-data-validation on aarch64 via pip using command "pip3 install tensorflow-data-validation" tries to build wheel from source code

**Problem description**
tensorflow-data-validation doesn't have wheel for aarch64 on PyPI repository. So, while installing tensorflow-data-validation via pip on aarch64 machine, pip builds the source code resulting in it takes more time to install tensorflow-data-validation. Making wheel available for aarch64 will benefit aarch64 users by minimizing tensorflow-data-validation installation time. We can release the wheel using CI/CD tools such as travis-ci, circle-ci, azure-pipelne etc. These tools will not just help us releasing wheels but also ensures the integrity of the product by running tests automatically on every PR/code change. Adapting these tools will make the developemt/integration process easy and fast.

**Expected Output**
Pip should be able to download tensorflow-data-validation wheel from PyPI repository rather than building it from source code.

@tensorflow-data-validation-team, please let me know if I can help you building wheel/uploading to PyPI repository and adding support for CI/CD. I am curious to make tensorflow-data-validation wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by gowthamkpr** [comment]
@odidev TFdv doesn't support aarch64 and that is the reason why you are seeing the following error

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 14 days. Please add additional comments forus to open this issue again. Thanks!

**Comment by abasu0713** [comment]
Is there any progress on this?
I am trying to build it from source using Bazel on a aarch64 machine so as to get the Tensorflow board working in Kubeflow on ARM. I would really appreciate any help..
```bash
(kf-image-build) alphaduriendur@hc-opi5p16-1:~/data-validation$ bazel version
Bazelisk version: v1.19.0
Build label: 7.1.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Mar 11 17:54:48 2024 (1710179688)
Build timestamp: 1710179688
Build timestamp as int: 1710179688
(kf-image-build) alphaduriendur@hc-opi5p16-1:~/data-validation$ conda list -n kf-image-build
# packages in environment at /home/alphaduriendur/miniconda3/envs/kf-image-build:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                      51_gnu  
blas                      1.0                    openblas  
brotli-python             1.0.9            py38h419075a_7  
ca-certificates           2023.12.12           hd43f75c_0  
certifi                   2024.2.2         py38hd43f75c_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
idna                      3.4              py38hd43f75c_0  
ld_impl_linux-aarch64     2.38                 h8131f2d_1  
libffi                    3.4.4                h419075a_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h6e398d7_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libopenblas               0.3.21               hc2e42e2_0  
libstdcxx-ng              11.2.0               h1234567_1  
ncurses                   6.4                  h419075a_0  
numpy                     1.24.3           py38h8708280_0  
numpy-base                1.24.3           py38h4a83355_0  
openssl                   3.0.13               h2f4d8fa_0  
packaging                 23.1             py38hd43f75c_0  
pip                       23.3.1           py38hd43f75c_0  
platformdirs              3.10.0           py38hd43f75c_0  
pooch                     1.7.0            py38hd43f75c_0  
pysocks                   1.7.1            py38hd43f75c_0  
python                    3.8.18               h4bb2201_0  
readline                  8.2                  h998d150_0  
requests                  2.31.0           py38hd43f75c_1  
scipy                     1.10.1           py38h7caaa05_1  
setuptools                68.2.2           py38hd43f75c_0  
sqlite                    3.41.2               h998d150_0  
tk                        8.6.12               h241ca14_0  
urllib3                   2.1.0            py38hd43f75c_1  
wheel                     0.41.2           py38hd43f75c_0  
xz                        5.4.6                h998d150_0  
zlib                      1.2.13               h998d150_0  
(kf-image-build) alphaduriendur@hc-opi5p16-1:~/data-validation$ python --version
Python 3.8.18
(kf-image-build) alphaduriendur@hc-opi5p16-1:~/data-validation$ python setup.py bdist_wheel
running bdist_wheel
running build
running bazel_build
ERROR: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package.
ERROR: /home/alphaduriendur/data-validation/tensorflow_data_validation/BUILD:3:15: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '//tensorflow_data_validation:windows'
ERROR: /home/alphaduriendur/data-validation/tensorflow_data_validation/BUILD:10:10: errors encountered resolving select() keys for //tensorflow_data_validation:move_generated_files
ERROR: Analysis of target '//tensorflow_data_validation:move_generated_files' failed; build aborted
INFO: Elapsed time: 0.235s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "setup.py", line 148, in <module>
    setup(
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
    self.run_command("build")
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 81, in run
    subprocess.check_call(
  File "/home/alphaduriendur/miniconda3/envs/kf-image-build/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/bazel', 'run', '-c', 'opt', '//tensorflow_data_validation:move_generated_files']' returned non-zero exit status 1.

```
