### ISSUE TITLE
_pywrap_tensorflow_data_validation.so: undefined symbol: PyInstanceMethod_New

### ISSUE THREAD

**Issue by dengyiping2014** [tensorflow/data-validation#17]
Dear guys,

I met a problem when using TFDV

import tensorflow_data_validation

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d00404091/myenv/local/lib/python2.7/site-packages/tensorflow_data_validation/__init__.py", line 22, in <module>
    from tensorflow_data_validation.api.validation_api import infer_schema
  File "/home/d00404091/myenv/local/lib/python2.7/site-packages/tensorflow_data_validation/api/validation_api.py", line 25, in <module>
    from tensorflow_data_validation.anomalies import pywrap_tensorflow_data_validation
  File "/home/d00404091/myenv/local/lib/python2.7/site-packages/tensorflow_data_validation/anomalies/pywrap_tensorflow_data_validation.py", line 28, in <module>
    _pywrap_tensorflow_data_validation = swig_import_helper()
  File "/home/d00404091/myenv/local/lib/python2.7/site-packages/tensorflow_data_validation/anomalies/pywrap_tensorflow_data_validation.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_data_validation', fp, pathname, description)
ImportError: /home/d00404091/myenv/local/lib/python2.7/site-packages/tensorflow_data_validation/anomalies/_pywrap_tensorflow_data_validation.so: undefined symbol: PyInstanceMethod_New

OS: ubuntu 16.04
bazel: 0.15
python: 2.7.12

I also updated swig to 3.0.12 and it seemed useless. Any other suggestions?

**Comment by paulgc** [comment]
Did you install TFDV using pip?

**Comment by dengyiping2014** [comment]
> Did you install TFDV using pip?

no, i installed it from source code.

**Comment by paulgc** [comment]
Can you check if installing using pip works? Make sure to uninstall TFDV before installing using pip.

**Comment by dengyiping2014** [comment]
yes, i have installed it from pip source, thank you. @paulgc .

**Comment by harshini-gadige** [comment]
Closing this issue as it has been resolved. Feel free to create a new issue if there is any similar problem related to this. Thank you !
